# Generated by Django 3.0 on 2023-07-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок изображения')),
                ('image', models.ImageField(unique=True, upload_to='stairs', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Pergola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок изображения')),
                ('image', models.ImageField(unique=True, upload_to='stairs', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок изображения')),
                ('image', models.ImageField(unique=True, upload_to='stairs', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Stair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок изображения')),
                ('image', models.ImageField(upload_to='stairs', verbose_name='Изображение')),
            ],
        ),
    ]
