# Generated by Django 3.0 on 2023-07-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fence',
            name='image',
            field=models.ImageField(unique=True, upload_to='fences', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pergola',
            name='image',
            field=models.ImageField(unique=True, upload_to='pergolas', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='image',
            field=models.ImageField(unique=True, upload_to='shelters', verbose_name='Изображение'),
        ),
    ]
