# Generated by Django 4.1 on 2023-12-03 10:27

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_projectvideo_alter_fence_id_alter_pergola_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='url',
            field=embed_video.fields.EmbedVideoField(default=1, verbose_name='Ссылка на видео'),
            preserve_default=False,
        ),
    ]
