# Generated by Django 4.1 on 2023-12-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_remove_projectvideo_video_projectvideo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvideo',
            name='description',
            field=models.TextField(default=1, max_length=1000, verbose_name='Описание видео'),
            preserve_default=False,
        ),
    ]
