# Generated by Django 4.1 on 2023-12-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_reviewvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvideo',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание видео'),
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание видео'),
        ),
    ]
