# Generated by Django 4.0 on 2024-05-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_projectvideo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок изображения')),
                ('image', models.ImageField(unique=True, upload_to='pergolas', verbose_name='Изображение')),
            ],
        ),
    ]
